version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME-app}
      - POSTGRES_USER=${POSTGRES_USER-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-postgres}
    ports:
      - ${POSTGRES_PORT-9002}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
